import {
  Globe,
  Mail,
  Video,
  Music,
  Code,
  FileText,
  ShoppingBag,
  BookOpen,
  Briefcase,
  Terminal,
  Cpu,
  Compass,
  Tv,
  MessageSquare,
  Share2,
  Bookmark,
  CheckSquare,
  Calendar,
  Cloud,
  Folder,
  Settings,
  Sparkles,
  Zap,
  Star,
  Search,
  Database,
  Layers,
  Heart,
  Headphones,
  Gamepad2,
  Camera,
  Film,
  MapPin,
  TrendingUp,
  Server,
  Key,
  Shield,
  Coffee,
  BookmarkCheck
} from 'lucide-react';
import React from 'react';

export const AVAILABLE_ICONS: { name: string; label: string; icon: React.ComponentType<{ className?: string; size?: number }> }[] = [
  { name: 'Globe', label: 'Web', icon: Globe },
  { name: 'Mail', label: 'E-mail', icon: Mail },
  { name: 'Code', label: 'Code', icon: Code },
  { name: 'Terminal', label: 'Terminal', icon: Terminal },
  { name: 'Cpu', label: 'Tech', icon: Cpu },
  { name: 'Video', label: 'Vidéo', icon: Video },
  { name: 'Tv', label: 'Streaming', icon: Tv },
  { name: 'Film', label: 'Cinéma', icon: Film },
  { name: 'Music', label: 'Musique', icon: Music },
  { name: 'Headphones', label: 'Audio', icon: Headphones },
  { name: 'MessageSquare', label: 'Chat', icon: MessageSquare },
  { name: 'Share2', label: 'Social', icon: Share2 },
  { name: 'ShoppingBag', label: 'Shopping', icon: ShoppingBag },
  { name: 'BookOpen', label: 'Lecture', icon: BookOpen },
  { name: 'FileText', label: 'Docs', icon: FileText },
  { name: 'Briefcase', label: 'Travail', icon: Briefcase },
  { name: 'Calendar', label: 'Calendrier', icon: Calendar },
  { name: 'CheckSquare', label: 'Tâches', icon: CheckSquare },
  { name: 'Gamepad2', label: 'Jeux', icon: Gamepad2 },
  { name: 'Sparkles', label: 'IA / Outils', icon: Sparkles },
  { name: 'Database', label: 'Données', icon: Database },
  { name: 'Server', label: 'Serveur', icon: Server },
  { name: 'Shield', label: 'Sécurité', icon: Shield },
  { name: 'Key', label: 'Identifiants', icon: Key },
  { name: 'TrendingUp', label: 'Finance / Bourse', icon: TrendingUp },
  { name: 'Camera', label: 'Photos', icon: Camera },
  { name: 'Compass', label: 'Exploration', icon: Compass },
  { name: 'Coffee', label: 'Pause / Blog', icon: Coffee },
  { name: 'Star', label: 'Favori', icon: Star },
  { name: 'Bookmark', label: 'Signet', icon: Bookmark },
  { name: 'BookmarkCheck', label: 'Important', icon: BookmarkCheck },
  { name: 'Zap', label: 'Productivité', icon: Zap },
];

export function getLucideIcon(iconName?: string): React.ComponentType<{ className?: string; size?: number }> {
  if (!iconName) return Globe;
  const found = AVAILABLE_ICONS.find((i) => i.name === iconName);
  return found ? found.icon : Globe;
}
